version: '2.3'

# create default network
#networks:
#  default:
#    external:
#      name: ros-network

services:

  ros2-sensor3d:
    #build: ./image
    image: wn1980/sensor3d-ros2${TAG}
    container_name: ros2_sensor3d
    init: true
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
    - ROS_DOMAIN_ID=50
    #  - ROS_MASTER_URI=http://master:11311
